Repository cloudposse/terraform-aws-s3-bucket, pull requests merged in 2022-01, with the labels that each got.

#125 Bump module versions and update GitHub workflows
  .github/auto-release.yml
  LICENSE
  README.md
  examples/complete/outputs.tf
  examples/complete/privileged-principals.tf
  examples/complete/replication.tf
  examples/complete/replication.us-east-2.tfvars
  examples/complete/variables.tf
  test/src/examples_complete_test.go
  test/src/go.mod
  test/src/go.sum
Labels: patch

#127 Fix: Change `s3_object_ownership` Description to Reflect All Possible Values
  README.md
  docs/terraform.md
  variables.tf
Labels: no-release

#92 Remove unused variable `abort_incomplete_multipart_upload_days`
  README.md
  docs/terraform.md
  examples/complete/variables.tf
  variables.tf
Labels: no-release

#115 Enable bucket key for reducing the cost of SSE-KMS with Amazon S3
  README.md
  docs/terraform.md
  examples/complete/fixtures.us-east-2.tfvars
  examples/complete/main.tf
  examples/complete/variables.tf
  main.tf
  variables.tf
Labels: enhancement, no-release
