Repository cloudposse/terraform-aws-s3-bucket, pull requests merged in 2023-05, with the labels that each got.

#170 Add support for permission boundaries on replication IAM role
  replication.tf
  variables.tf
Labels: no-release

#178 Make compatible with new S3 defaults. Add user permissions boundary.
  README.md
  docs/terraform.md
  main.tf
  replication.tf
  variables.tf
Labels: minor

#180 Revert change to Transfer Acceleration from #178
  README.md
  docs/terraform.md
  examples/complete/main.tf
  examples/complete/privileged-principals.us-east-2.tfvars
  examples/complete/variables.tf
  main.tf
  variables.tf
Labels: bugfix

#183 Sync .github
  .github/auto-release.yml
  .github/workflows/auto-context.yml
  .github/workflows/auto-format.yml
  .github/workflows/auto-readme.yml
  .github/workflows/auto-release.yml
  .github/workflows/chatops.yml
  .github/workflows/feature-branch-chatops.yml
  .github/workflows/feature-branch.yml
  .github/workflows/release-branch.yml
  .github/workflows/release-published.yml
  .github/workflows/scheduled.yml
  .github/workflows/validate-codeowners.yml
Labels: no-release
