Repository cloudposse/terraform-aws-s3-bucket, pull requests merged in 2024-11, with the labels that each got.

#250 fix: correct bucket name to fix broken `-replication` role
  replication.tf
Labels: patch

#256 fix: use new destination.bucket key in policy
  replication.tf
Labels: patch, bugfix

#255 feat: support eventbridge bucket notification
  README.md
  docs/terraform.md
  main.tf
  variables.tf
Labels: triage
